apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-pipeline-app
  labels:
    app: node-pipeline-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-pipeline-app
  template:
    metadata:
      labels:
        app: node-pipeline-app
    spec:
      containers:
        - name: node-app
          image: DOCKERHUB_USERNAME/github-pipeline-demo:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"